"""update tables for new models

Revision ID: 71f664d79e3b
Revises: d16618bfec8d
Create Date: 2025-05-16 17:07:42.021782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '71f664d79e3b'
down_revision = 'd16618bfec8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
