"""update order model

Revision ID: 74c5dabc6703
Revises: 71f664d79e3b
Create Date: 2025-05-16 17:42:53.019314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '74c5dabc6703'
down_revision = '71f664d79e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('order', sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column(
        'order',
        'order_date',
        existing_type=sa.VARCHAR(),
        type_=sa.DATE(),
        postgresql_using="order_date::date"
    )
    op.alter_column(
        'order',
        'total_price',
        existing_type=sa.VARCHAR(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
        postgresql_using="total_price::numeric(10,2)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('order', 'order_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('order', 'store_name')
    op.drop_column('order', 'order_type')
    # ### end Alembic commands ###
