"""add store models

Revision ID: d16618bfec8d
Revises: 1a31ce608336
Create Date: 2025-05-16 16:44:07.819208

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd16618bfec8d'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('fdc_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('unit_size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('upc_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('brand_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_fdc_id'), 'food_items', ['fdc_id'], unique=True)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_index(op.f('ix_food_items_upc_code'), 'food_items', ['upc_code'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('unit_size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('upc_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('brand_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_upc_code'), 'products', ['upc_code'], unique=True)
    op.create_table('stores',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('store_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_total', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('price_history',
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_availability',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upc_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('store_product_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('store_product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('product_availability')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_products_upc_code'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('order')
    op.drop_index(op.f('ix_food_items_upc_code'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_fdc_id'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
